"use strict";

/* GENERAL EXPLANATION:
-> FIRST CLASS FUNCTION IS A CONCEPT IN JAVASCRIPT IN WHICH WE BASICALLY CHECK OR DEFINE THE POSSIBLE BEHAVIOUR OF FUNCTIONS.
-> FIRST CLASS FUNCTIONS ARE SIMPLY TREATED AS VALUES.
-> FUNCTIONS ARE ANOTHER TYPE OF OBJECT.

-> WE CAN STORE FUNCTION IN A VARIABLE.
-> WE CAN PASS FUNCTION AS AN ARGUMENT TO OTHER FUNCTION.
-> WE CAN RETURN FUNCTION  FROM ANOTHER FUNCTION.
-> WE CAN CALL METHOD FROM FUNCTIONS AS IT IS THE OTHER TYPE OF OBJECT.
-> CALL BACK FUNCTIONS ARE ALSO FIRST CLASS FUNCTIONS.

-> HIGHER ORDER FUNCTIONS RECIEVES ANOTHER FUNCTION AS AN ARGUMENT AND RETURNS BOTH OR A NEW FUNCTION.

-> HIGHER ORDER FUNCTIONS ARE ADDEVENTLISTENERS , FUNCTION THAT USE ANOTHER FUNCTION AS AN ARGUMENT .

*/
