"use strict";

/* GENERAL EXPLANATION:

-> THE FIND METHOD:
-> FIND METHOD IS ONE OF THE USEFUL METHOD OF THE ARRAY , IN WHICH WE CAN GET OR RETREIVE ONE ELEMENT OF AN ARRAY , THAT SATISFY THE GIVEN CONDITION.
-> WHEN WE GIVE A CONDITION TO IT , THEN THE CONDITION WILL SIMPLY GET THAT FIRST ELEMENT OF THE ARRAY THAT SATISFY THAT CONDITION.
-> LIKE IF WE HAVE AN ARRAY OF POSITIVE NUMBERS , AND I GIVE A CONDITION THAT IS NUMBER  > 0 , IT WILL SIMPLY APPLY ON THE FIRST POSITIVE NUMBER OF THE ARRAY WHICH IS GREATER THAN ZERO.

-> THERE IS A DIFFERENCE BETWEEN FILTER AND FIND METHOD ,  WE GIVE CONDITION TO BOTH , BUT THE FILTER METHOD WILL GET ALL THE ARRAY , AND FIND METHOD WILL GET ONLY THE ELEMENT OF THE ARRAY WHICH SATISFY THE CONDITION.

*/

const coins = [233, 11, 234, -1233, -300, 123, 456, 234, -16000];
const find = coins.find((coin) => coin > 400);
console.log(find); // 456
