"use strict";

/* GENERAL EXPLANATION:

-> THE SOME METHOD:
-> AS THE NAME ITSELF SAYS , IT CHECK THE CONDITION IF ITS TRUE OR FALSE, LIKE IF THERE IS SOME ELEMENTS IN AN ARRAY THAT ARE GREATER THAN ZERO SO IT RETURN TRUE EVEN IF IT IS ONLY ONE ELEMENT IN THE ENTIRE ARRAY.
-> IT IS HIGHER ORDER FUNCTION.

-> THE EVERY METHOD:
-> IN EVERY METHOD , THE CONDITION SHOULD PASS THE ENTIRE ARRAY ELEMENTS OTHERWISE IT WILL RETURN FALSE .
-> IT IS ALSO HIGHER ORDER FUNCTION.

*/

const coins = [200, 450, -400, 3000, -650, -130, 70, 1300];

// EQUALITY
// IT WILL ONLY RETURN TRUE IF IT HAS THE EXACT NUMBER IN THE CONDITION.
console.log(coins.includes(200)); // TRUE

// CONDITION:
console.log(coins.some((coin) => coin > 0)); // TRUE
console.log(coins.some((coin) => coin < -1500)); // FALSE
//  WE USED SOME METHOD IN THE BANKIST PROJECT TO IMPLEMENT FUNCTIONALITY TO REQUEST A LOAN FROM THE BBANK.

console.log(coins.every((coin) => coin > 0)); // FALSE
